# Generated by Django 2.2 on 2019-04-07 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accountant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrequest',
            name='account_link',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_link', to='Accountant.Account'),
        ),
    ]
