# Generated by Django 2.1.1 on 2019-04-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=127)),
                ('email', models.EmailField(max_length=127)),
                ('institute_name', models.CharField(max_length=127)),
                ('institute_iso', models.CharField(max_length=127)),
            ],
        ),
    ]
