# Generated by Django 2.2 on 2019-04-07 12:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_password', models.CharField(max_length=127)),
                ('db_engine', models.CharField(max_length=127)),
                ('db_name', models.CharField(max_length=127)),
                ('db_user', models.CharField(max_length=127)),
                ('db_password', models.CharField(max_length=127)),
                ('db_host', models.CharField(max_length=127)),
                ('db_port', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=127)),
                ('email', models.EmailField(max_length=127)),
                ('institute_name', models.CharField(max_length=127)),
                ('institute_iso', models.CharField(max_length=127)),
                ('approved', models.BooleanField(default=False)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval_date', models.DateTimeField(null=True)),
                ('status', models.CharField(default='Inactive', max_length=63)),
                ('account_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_link', to='Auth.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Auth.AccountRequest'),
        ),
    ]
