# Generated by Django 2.1.1 on 2019-04-05 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_accountrequest_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
