# Generated by Django 2.2 on 2019-05-06 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=31)),
                ('city', models.CharField(max_length=31)),
                ('state', models.CharField(max_length=31)),
                ('pincode', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=31)),
                ('email', models.EmailField(max_length=31)),
                ('password', models.CharField(max_length=31)),
                ('first_name', models.CharField(max_length=31)),
                ('last_name', models.CharField(max_length=31)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('start_date', models.DateField()),
                ('address_link', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='Profiler.Address')),
                ('contacts_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Person'),
        ),
    ]
