# Generated by Django 2.2 on 2019-06-05 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('duration', models.CharField(max_length=31)),
                ('description', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('dept_code', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=31)),
                ('semester', models.CharField(max_length=31)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('theory_prac', models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical')], default='Theory', max_length=31)),
                ('isRemedial', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Profiler.Person')),
                ('designation', models.CharField(max_length=31)),
                ('qualification', models.CharField(max_length=31)),
            ],
            bases=('Profiler.person',),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_theory', models.BooleanField(default=False)),
                ('duration', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Profiler.Person')),
                ('roll_no', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('admission_type', models.CharField(max_length=31)),
                ('is_d2d', models.BooleanField(default=False)),
                ('degree', models.CharField(max_length=31)),
                ('cast_category', models.CharField(max_length=31)),
                ('nationality', models.CharField(max_length=31)),
                ('blood_group', models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=31)),
                ('guardian_name', models.CharField(max_length=31)),
                ('guardian_relation', models.CharField(max_length=31)),
            ],
            bases=('Profiler.person',),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('semester', models.CharField(max_length=31)),
                ('credits', models.CharField(max_length=31)),
                ('description', models.CharField(max_length=31)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Course')),
                ('session', models.ManyToManyField(to='Profiler.Session')),
            ],
        ),
        migrations.CreateModel(
            name='ToBeCovered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='contacts_link',
        ),
        migrations.AddField(
            model_name='contact',
            name='Person_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='Profiler.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='Profiler.Address'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('description', models.CharField(max_length=31)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Subject')),
                ('to_be_covered', models.ManyToManyField(to='Profiler.ToBeCovered')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thu'), ('Friday', 'Fri'), ('Saturday', 'Sat')], max_length=31)),
                ('seq_no', models.IntegerField()),
                ('start_time', models.DateField()),
                ('location', models.CharField(max_length=31)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Division')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Session')),
                ('to_be_covered', models.ManyToManyField(to='Profiler.ToBeCovered')),
            ],
        ),
        migrations.CreateModel(
            name='SessTheory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='SessPrac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('max_marks', models.IntegerField()),
                ('duration', models.CharField(max_length=31)),
                ('date_of_exam', models.DateField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyIncharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ManyToManyField(to='Profiler.Faculty')),
                ('subject', models.ManyToManyField(to='Profiler.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Department'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Division')),
                ('sess_prac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profiler.SessPrac')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(False, 'Absent'), (True, 'Present')], default=False)),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Student')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler.TimeTable')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='Dep_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='Profiler.Department'),
        ),
    ]
